name: Run Flask Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Update to the Python version you need
    - name: Set extra path
      run: echo "./coffee_shop_backend" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt  # Ensure requirements.txt includes Flask, pytest, Flask-Testing

    - name: Run Unit Tests
      run: |
        source venv/bin/activate
        pytest test_app.py  # Update with the path to test_app.py